### ISSUE TITLE
Errata.md page numbers shifted

### ISSUE THREAD

**Issue by ThiesDS** [aloctavodia/BAP#30]
Hey, 

I was just about to report some typos in the second edition of the book and update the errata.md as I noticed that for the second chapter the page numbers are shifted one down. E.g. the typo reported in the errata on page 59 is actually on page 60 in the book. 

Did I miss something or do we need to correct the errata.md? 

Best
Sven

**Comment by aloctavodia** [comment]
Hi @ThiesDS thanks for your help. The layout is slightly different between the printed and digital version. The page numbers currently reported in the errata are from the digital version. I will add the page numbers for the printed version ASAP. Sorry about the confusion.

**Comment by aloctavodia** [comment]
Fixed! thank you @ThiesDS
