### ISSUE TITLE
A question on chapter 2

### ISSUE THREAD

**Issue by javabean68** [aloctavodia/BAP#32]
Hi Osvaldo

first off compliments on your book. I'm reading it on Safari and I decided to purchase the paper edition as well. 
Sorry for my silly questions as I am learning this matter the first time.

In Model specification (chapter 2) it reads 'For the likelihood, we will use the binomial distribution with n=1'

A binomial distribution with n =1 is equivalent to a Bernoulli one. Right?

In the image 2.1 I would then expect _y ~ B(n=1, p=Theta)_ or  _Bern(p=Theta)_ instead of _Bern(n=1, p=Theta)_

That means also we are re-coding only a sub-case of the previous chapter where **n** had no limitations?
if so, how could we code the same case in PyMC3?
I am a bit confused.

Thank you for your help,
Regards
Fabio

**Comment by aloctavodia** [comment]
Hi Fabio,

I am glad you are enjoying the book.

You are right, the binomial distribution with n=1 is the bernoulli distribution. So expression 2.1 should be  y ~ B(n=1, p=Theta) or Bern(p=Theta) (as you said). Sorry for the confusion, I will add this to the errata.

Regarding your last question: 

Assuming `data` is a collection of zeros and ones, using either of the commented expressions should give the same estimation for θ.

```python
with pm.Model() as model:
    θ = pm.Beta('θ', alpha=1, beta=1)
    #y = pm.Bernoulli('y', p=θ, observed=data)
    #y = pm.Binomial('y',n=n_trials, p=θ, observed=sum(data))
```

I hope this helps clarify your confusion.

**Comment by javabean68** [comment]
Super! Thank you: I'll give 5 stars to you on Safari and Amazon :-)

Ciao
