### ISSUE TITLE
A Typo on Cohen's d

### ISSUE THREAD

**Issue by javabean68** [aloctavodia/BAP#33]
Hi Osvaldo,

I found a typo on the Cohen's d definition 2.4 on page 67 : sigma2^2 - sigma1^2. (- instead of +)

I'm enjoying your book but I have some difficulties to understand the meaning of the method _sample_ on the model.

For example on page 70 when you analyze the _tip_ dataset and write:
 `trace_cg = pm.sample(5000)`
my guess is that 5000 samples are drawn from the mu interval  and 5000 from the sigma interval  and that for every such couple of values is done what you have described in the first chapter.

That's to say for the corresponding prior distribution is evaluated the likelihood under the data values and this is the multiplied by the prior getting so the posterior distribution of sigma and mu ...but then? How can you derive the global distribution as in figure 2.10? I suppose the values are somewhat aggregated, summed and normalized? 

Thank you very much for your help in advance,
Bye
Fabio

**Comment by aloctavodia** [comment]
Hi Fabio,

Thanks for reporting the error. Notice that this have been previously reported and is listed in the errata.md and errata.pdf files (you can find both files in this repository).

Regarding you question.  `pm.sample` returns a sample from the joint distribution of parameters, for the `model_g` example the joint distribution is bidimensional (`mu` and `sigma`). So if you inspect the `trace` object you will see pairs of values (`mu`, `sigma`). Figure 2.10 is done using two 1 dimensional KDEs (the individual or marginal distributions of `mu` and `sigma`) and one 2 dimensional KDE (the joint distribution of `mu` and `sigma`). Conceptually a [Kernel Density Estimation](https://en.wikipedia.org/wiki/Kernel_density_estimation) (KDE) works as follow, place a gaussian distribution with a given variance "on top" of each data point then choose a grid over the range of your data and at each grid-point sum the contributions from all gaussian. A KDE is a non-parametric non-Bayesian way to approximate an arbitrary density you will find more information on chapter 6 mixture models.

The following block of code shows how to make a KDE plot and also shows the gaussians you sum (called kernels)

```python
import matplotlib.pyplot as plt
import scipy.stats as stats
import numpy as np
import arviz as az
az.style.use('arviz-white')

_, ax = plt.subplots(figsize=(12, 4))
bw = 0.4
np.random.seed(42)
y = np.random.normal(8, size=8)
x = np.linspace(y.min() - bw * 3, y.max() + bw * 3, 100)
kernels = np.transpose([stats.norm.pdf(x, i, bw) for i in y])
ax.plot(x, kernels, 'k--', alpha=0.5)
ax.plot(y, np.zeros(len(y)), 'C1o')
ax.plot(x, kernels.sum(1))

ax.set_xticks([])
ax.set_yticks([])
ax.set_linewidth() = 0
```

Please, let me know if this answer your question or if you have more questions.

**Comment by javabean68** [comment]
Hi Osvaldo,

many thanks for your explanation!

Bye
Fabio
