### ISSUE TITLE
Page 128

### ISSUE THREAD

**Issue by RogerS49** [aloctavodia/BAP#34]
Figure 3.22 and it's description paragraph immediately below do not match. The description describes m_x2 is around 0.55 when in the diagram it is shown around  -0.2. Either the figure is wrong or the description is wrong. I think it should be this figure

![B11197_03_22](https://user-images.githubusercontent.com/9880714/59250915-6ef67b00-8c20-11e9-811b-17facc5ddeec.png)

and not this 
 
![Screen Shot 2019-06-11 at 08 12 35](https://user-images.githubusercontent.com/9880714/59251048-c399f600-8c20-11e9-85c3-df7d36205943.png)

**Comment by aloctavodia** [comment]
Sorry about that. You are right the correct figure is the first you posted. I have added a line to the errata clarifying this. Notice that the figure in this repository is the correct one.
