### ISSUE TITLE
within-sample vs out-of-sample accuracy

### ISSUE THREAD

**Issue by djmannion** [aloctavodia/BAP#35]
"For any combination of data and models, the within-sample accuracy will be, on average, smaller than the out-of-sample accuracy." (p. 190)

Shouldn't within-sample and out-of-sample be switched in the above? Perhaps I am reading it wrong.

**Comment by aloctavodia** [comment]
I am thinking on a measure of "accuracy" that the smaller the best, like WAIC or LOO.

**Comment by djmannion** [comment]
Ah, I see - thanks for the clarification!
