### ISSUE TITLE
Should var_names be x_4, y_4?

### ISSUE THREAD

**Issue by canyon289** [aloctavodia/BAP#38]
Looking at model_t2 at the bottom should the array names be `x_4` and `y_4`? If so I can make a PR, just wanted to double check first.

https://github.com/aloctavodia/BAP/blob/master/code/Chp3/03_Modeling%20with%20Linear%20Regressions.ipynb

<img width="799" alt="image" src="https://user-images.githubusercontent.com/7213793/60761938-2eb8cb80-a019-11e9-8805-d5d26b1a9e29.png">

**Comment by aloctavodia** [comment]
You are totally right!

**Comment by canyon289** [comment]
Fixed in a PR
