### ISSUE TITLE
Dos últimos modelos del cap. 8 no funcionan

### ISSUE THREAD

**Issue by rosgori** [aloctavodia/BAP#4]
Los dos últimos modelos (`GP` y `GP_periodic`) del cap. 8 no funcionan con `pymc3` versión 3.3. Para solucionar esto, cambiar

`trace = pm.sample(1000)` 

a 

`trace = pm.sample(1000, njobs=1)`.

Los dos modelos mencionados sí funcionan con `pymc3` versión 3.2

**Comment by aloctavodia** [comment]
Gracias por el reporte! 

Una aclaración `njobs` ha sido marcado como obsoleto, en la próxima versión (3.4) habrá que usar `cores`
