### ISSUE TITLE
Fig 3.22 is a duplicate of fig 3.26

### ISSUE THREAD

**Issue by jdhare** [aloctavodia/BAP#53]
Fig 3.22 does not match the text describing it, or the output of the code sample provided. Instead, it is an accidental duplicate of Fig 3.26.

**Comment by jdhare** [comment]
Apologies, 3.22 is a duplicate of fig 3.27, not 3.26

**Comment by aloctavodia** [comment]
Thanks for taking the time to report this. This issue has already been addressed, please check the errata.
