### ISSUE TITLE
Typos Chapter 7

### ISSUE THREAD

**Issue by simonsteinberg** [aloctavodia/BAP#55]
First of all, thanks for sharing your knowledge and writing this book. I really enjoyed working it through. I thought, you'd might appreciate if I let you know about typos I found. If I am mistaken, I am sorry for the inconvenience

* p. 257 (I am referring to the page numbers of the print version), I think the sentence  `For the purpose ...  returns a value of >zero< i>n< ...` should be changed to `For the purpose ... returns a value of one if ...`, compare to eq. (7.3).
* p.264, I think there is a code line missing `trace_reg = pm.sample(...)`.
* p.269, in text you say that you will use column `lon2`. Later in the code example, however, you used the `lon` - column, i.e., `x_data = [ ... , islands.lon.values[:, None]]`.

**Comment by aloctavodia** [comment]
Thanks for taking the time to report this typos. You are right about all of them. Regarding the last one I see that `x_data` is defined but never use. So while it is correct that we only use `lon2`· The line `x_data = [ ... , islands.lon.values[:, None]]` should be deleted.
