### ISSUE TITLE
Typos Chapter 3

### ISSUE THREAD

**Issue by simonsteinberg** [aloctavodia/BAP#56]
* p.123 (print version), eq. (3.16), I think there is a problem with the dimension of `X`
  - If `X` is an `(m x n)`-Matrix (as stated in the book), then beta should be a `(1 x m)`-vector (row-vector) and eq. (3.16) should read as `mu = alpha * ones(1, n) + beta * X`. Accordingly, `mu` is  also a `(1 x n)`-vector (row-vector).
  - If `X` were an `(n x m)`-Matrix, then eq. (3.16) is OK, i.e., `mu = alpha * ones(n, 1) + X * beta`. Now, `mu` is  an `(n x 1)`-vector (column-vector).

* p.123, eq. (3.17), I believe the sum should run from `i = 1` to `n` (not `m`)

**Comment by aloctavodia** [comment]
Thanks for taking the time to report this typos. I will add them to the errata.
