### ISSUE TITLE
Chapter 3 exercises - Question 5

### ISSUE THREAD

**Issue by bjonnh** [aloctavodia/BAP#59]
dataset.prior["y,"]  raises a KeyError.

**Comment by aloctavodia** [comment]
did you try `dataset.prior["y"]`?

**Comment by bjonnh** [comment]
Nope doesn't work either. Problematic cell is: prior_predictive = dataset.prior["y,"].values.flatten()

**Comment by bjonnh** [comment]
"In [10]" of Question 5

**Comment by aloctavodia** [comment]
Sorry to insist but it seems you are writing `["y,"]`, with a comma, instead of `["y"]`. If this is not the problem could post a minimal reproducible example?

**Comment by bjonnh** [comment]
It is not me adding the comma, it is you:

In the file:
https://github.com/aloctavodia/BAP/blob/master/exercises/Chapter3.ipynb

In question 5:

In [10]:

print(dataset.prior["y,"].values.shape)
prior_predictive = dataset.prior["y,"].values.flatten()
prior_predictive.shape

**Comment by aloctavodia** [comment]
OK, It was not clear to me you were talking about the solved exercises in the repo and not something in the book. With the last versions of arviz you have to use the `prior_predictive` group instead of the `prior` one. 

`dataset.prior_predictive["y,"].values.flatten()`
