### ISSUE TITLE
two small typos in equations in chapter 5

### ISSUE THREAD

**Issue by arunpersaud** [aloctavodia/BAP#61]
in 5.14:  I think in the term with the 1/S the sum should run up to 'S' not 's' (but perhaps it is already a capital s and I just have font size issues;))

in 5.18: terms in the second line have the wrong sign, e.g. the q_i term should be '-' and the r_i term '+' 

things I'm not sure about:
* comparing 5.5 and 5.6 I'm also wondering if in 5.5 pAIC should be p_{AIC}?
* 5.7 and 5.14 are the only places where you use a \sum^{N}_{i} without giving a starting value for i, that is everywhere else you write  \sum^{N}_{i=1}  or just \sum_i without an end value (perhaps in 4.16 the sum should gain a 'k', since it is the only place I found that doesn't have an index). 5.7 is also the only place I could find where the indices are to the right of the sum symbol and not on top and bottom

**Comment by aloctavodia** [comment]
Thanks for your comments, I will add them to the errata.
