### ISSUE TITLE
Chapter 4 - exercises question 8

### ISSUE THREAD

**Issue by bjonnh** [aloctavodia/BAP#63]
trace_logistic = pm.sample(size=2000)

should be

trace_logistic = pm.sample(2000)

**Comment by aloctavodia** [comment]
I am not able to find the offending line in the book or notebooks. Are you sure this is a typo from the book. Could you point to the page number and if this is the printed or ebook version. Thanks

**Comment by bjonnh** [comment]
Not in the book, it is in the exercise notebooks of this repo. Arviz PyMC are the last in anaconda.

**Comment by aloctavodia** [comment]
Fixed!
