### ISSUE TITLE
Confounding variables and redundant variables chapter 

### ISSUE THREAD

**Issue by jaircastruita** [aloctavodia/BAP#64]
"As we can see, \beta_2 for model m_x1x2 is around zero, indicating an almost null contribution of the x_2 variable to explain  y. "

The image in contrast shows a negative value far away from 0 for this coefficient.

**Comment by aloctavodia** [comment]
Hi @jaircastruita thanks for your comment.

This have been solved, please check the errata for the first printing.

**Comment by jaircastruita** [comment]
you´re right. I re-downloaded the book from the official page and the image is corrected. Thanks!
