### ISSUE TITLE
Any plans to port to other frameworks ?

### ISSUE THREAD

**Issue by hotessy** [aloctavodia/BAP#65]
Hey @aloctavodia,
I loved your book as a beginner. This repository, in itself, is immensely helpful.   
Do you have any plans to port the examples to other frameworks like [pyro](https://pyro.ai/), [edward](http://edwardlib.org/) or pymc4?

**Comment by aloctavodia** [comment]
Hi @hotessy, glad you like the book. I would like to port the examples to pymc4 and bambi, but I do not have time at the moment. Maybe during the second semester.
