### ISSUE TITLE
Issue with installing theano and pymc3 on PyCharm

### ISSUE THREAD

**Issue by rsinganal** [aloctavodia/BAP#67]
There has been particular issue with installing both theano and pymc3 on PyCharm. I have tried multiple install/uninstall with both pip and conda and nothing has worked till now. The error message I get is linked to theano. Please let me know how to solve this issue.

**Comment by canyon289** [comment]
Hi there!
Glad you're enjoying the book. I don't see an error posted but have some guidance.

* Pycharm is an Integrated Development Environment. It itself doesn't install pymc3 or theano, but uses an underlying environment manager like venv, pip, conda, etc. To get to the root of this can you confirm which one it's using?
* I use pycharm with conda nearly exclusively and things are "working for me". I know that doesn't fix your issue but want you to know there's hope!

Looking forward to that error message

**Comment by rsinganal** [comment]
<img width="1273" alt="Screen Shot 2020-05-24 at 1 57 59 PM" src="https://user-images.githubusercontent.com/63841251/82771313-2dc99c00-9e6e-11ea-9036-c078d3b4b25e.png">

**Comment by rsinganal** [comment]
There you go with the error message

**Comment by rsinganal** [comment]
As I mentioned before, I used both pip and conda to install theano and pymc3 on PyCharm. And yes, I am aware that PyCharm is an IDE.

**Comment by canyon289** [comment]
Looks like this could be one of many issues. Could you try the solutions posted in this thread? https://github.com/Theano/Theano/issues/6645

**Comment by rsinganal** [comment]
Yes, it seems like an issue with theano and lazylinker too. And many people have posted a similar error all over the internet. I wanted to use pymc3 for Bayesian statistics but looks like I will have to give up.

**Comment by rsinganal** [comment]
Can Arviz be used as a replacement for pymc3 for the code in the book with some modifications in the code?

**Comment by canyon289** [comment]
Er not quite PyMC3 is the bayesian inference engine, and ArviZ is the visualization package. You'll need both.

It's hard to debug over the internet but perhaps as another suggestion, you could use docker and jupyter notebooks instead of pycharm. If that sounds alright I can send you some tips of how to get both working.

Sincere apologies on the trouble, getting an environment setup can be quite frustrating. I've probably spent days of my life debugging env issues tbh.

**Comment by rsinganal** [comment]
Could you send me information about how to use it via docker and Jupyter? It'd be most helpful.

**Comment by canyon289** [comment]
Of course, 
I have instructions for how to setup a pymc, arviz environment in this tutorial I wrote. There are 4 different ways to get things running, including the docker one, so I hope one of these works for you.

https://github.com/canyon289/bayesian-model-evaluation

**Comment by rsinganal** [comment]
Thank you Ravin. I will check it out.
