### ISSUE TITLE
Confusion about the Regression with spatial autocorrelation sample of Ch7

### ISSUE THREAD

**Issue by xwk** [aloctavodia/BAP#68]
I'm quite confused about what is the x value for each island when computing the exponential quadratic kernel function value in the sample code.

From the line , `f = gp.prior('f', X=islands_dist_sqr)`,  the x value for island i should be the ith column of the islands_dist_sqr 2-D matrix, which is to say, the x values for the kernel function should be vectors (with length=10)

However, the code for generating Fig 7.9 apparently assume x is a scalar value. Moreover the code which computs the exponential quadratic kernel function for Fig 7.9 does not look right. It computes exp(-ℓ *(x1-x2)^2), but the defintion of exponential quadratic kernel  is exp(-(x1-x2)^2/(2*ℓ ^2)

**Comment by aloctavodia** [comment]
Sorry for the late response. Let me check the code and text in the book and I will come back to you ASAP.

**Comment by aloctavodia** [comment]
In figure Fig 7.9 you are trying to get intuition on how the covariance change with distance, the explicit information about pairwise distances is lost. Figure 7.10 show that information and also the dataframe with the "median covariance among societies". 

You are right about the exponential quadratic kernel.
