### ISSUE TITLE
Add pip to bap.yml file

### ISSUE THREAD

**Issue by anzelpwj** [aloctavodia/BAP#72]
I just ran `conda env create -f bap.yml` (conda version 4.8.3) and it complained

```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```

Might as well stop conda from nagging us?

**Comment by anzelpwj** [comment]
FWIW, I'm happy to do this if this issue is approved.

**Comment by canyon289** [comment]
PAULLL!! I am so excited you are here. Thanks for reporting this bug. Keep em coming

**Comment by canyon289** [comment]
And the issue is approved. Go ahead do it.
