### ISSUE TITLE
Understanding the plot_trace

### ISSUE THREAD

**Issue by carlryn** [aloctavodia/BAP#75]
Hej, 

First I'd like to thank you for a great book! It's a pleasure reading through it.
There is something fundamental that I have not understood and is not explained in the book. This is the ArviZ plot_trace. 
![Screenshot from 2020-12-23 11-55-56](https://user-images.githubusercontent.com/17131441/102989429-e398be00-4515-11eb-8708-00d15b733383.png)

For theta there is one blue and one orange line. Why not just one? Is it one per chain?

**Comment by AlexAndorra** [comment]
Hi @carlryn !
Exactly, there is on color per chain. On the left is the inferred posterior KDE, and on the right are all the values taken by the Markov chains (here there are 2) during their 1000 simulations.

You want this right plot to look like a caterpillar (i.e as close as possible to random noise), so this one is looking quite good. You can ask PyMC3 to take more draws if you want (e.g 2000 per chain), and you'll see that these plots should converge even more, to a point where you can't really discriminate between the chains.

Hope this helps, and enjoy your holiday reading 🖖 🎄
