### ISSUE TITLE
module 'arviz' has no attribute 'geweke'

### ISSUE THREAD

**Issue by rlagare** [aloctavodia/BAP#77]
Whenever I run the code examples on Jupyter notebook, and on the part where you import pymc3, I get the error, "module 'arviz' has no attribute 'geweke'". This only happens when I import pymc3, which is all chapters. I was only able to run the code examples in chapter 1, because it did not require importing pymc3. 

attached is a snapshot of the error message:

![error](https://user-images.githubusercontent.com/70551160/113468616-2de2e280-9415-11eb-8df3-9ea3381d55c3.png)

Please help.

**Comment by canyon289** [comment]
Hi,
Can you verify the versions youre installing match whats in this environment file?
https://github.com/aloctavodia/BAP/blob/master/bap.yml

**Comment by rlagare** [comment]
I can confirm that I downloaded the bap.yml file, and installed the necessary packages by doing "conda env create -f bap.yml" via anaconda prompt. After doing that, I did check my python version and it was 3.7.9, even though the bap.yml file states 3.6.

I am relatively new with Python, so I don't really know what I am doing. I am simply following the instructions stated in the book/github.

**Comment by rlagare** [comment]
I also tried activating the bap env before opening Jupyter Notebook, but the errors get even worse. Here is a snapshot: 

![image](https://user-images.githubusercontent.com/70551160/113486629-de86cb80-9481-11eb-8e6b-6debe1c76516.png)

**Comment by canyon289** [comment]
@rlagare dont worry this isnt your fault. This is an unfortunate but common impedement when trying to setup an environment the first time. 

What operating system are you working on? Ill try and work through this with you

**Comment by rlagare** [comment]
sounds great, @canyon289. I am using windows 10.

**Comment by rlagare** [comment]
I appreciate this, Ravin. I am using Windows 10.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by canyon289** [comment]
Alright so first off, this is frustrating and I want you to know its not you, its the computer. I've been doing this for a living for basically 6 years now and this one was a doozy.

First off installing open source computational tools on windows is notoriously annoying and hard. Because of that I would suggest using  Google Colab https://colab.research.google.com/

I ended creating a video to you how to get things working.
https://www.youtube.com/watch?v=eapFqL3fZSg&ab_channel=RK

Here's the code needed to get everything installed
`!pip install matplotlib==3.0.2 pymc3==3.6 pandas==0.23.4 seaborn==0.9 scipy==1.1 arviz===0.3.1`

@aloctavodia tagging you in case other people have issues, you can see that this resource exists

**Comment by rlagare** [comment]
I appreciate this very much, Ravin. I just saw the video, and I am able to follow the code examples now. Thanks!

Also, I go by Rex; that's the "R" in rlagare, and thanks for the introduction to Google Colab. It seems pretty neat, although I am missing the variable explorer feature that you get when using Spyder.

I am still unclear how I feel about Colab though, perhaps my opinion would be better formed as I use it in the future. I do hope that I could still solve the "OSS" problem and be able to pymc3 and arviz using Spyder or even Jupyter Notebook.

Regardless, I am happy that I can move forward with learning from the BAP book.

Cheers!




Rexonni Lagare

***@***.***

________________________________

**Comment by canyon289** [comment]
Rex, I totally understand. Every development environment has its upsides and downsides. In practice I use a different one depending on what I'm doing.

Spyder is quite nice, but as you figured out youll have to figure out how to get the dependencies to work and its unfortunately challenging.

What I would suggest is doing both. Use the colab to learn from the book, but then see if you can install a brand new environment of your own on your desktop computer and reimplement the pieces of the example that are interesting to you to get the best of both worlds!

Above all through really glad youre able to get started!! Thank you for your patience
