### ISSUE TITLE
Add section for links to books in readme

### ISSUE THREAD

**Issue by darigovresearch** [aloctavodia/BAP#83]
Thought it may be helpful to add a link to where the books can be found.

A link to the packt version is in the introduction & the amazon is in the repo about section (which most people can overlook if they don't know about the about section.

Thought it may be helpful to have an explicit section in the readme to find the books in case they stumble on the repository first.

An example is in the following format with explanations so people can choose if they want to use an affiliate link as an example

### Non-affiliate links
- Packt link (non affiliate link)
- Amazon US link (non affiliate link)
- Amazon UK link (non affiliate link)

### Affiliate links
- Packt link (affiliate link if any)
- Amazon US link (affiliate link if any)
- Amazon UK link (affiliate link if any)

**Comment by aloctavodia** [comment]
Good idea! I don't have affiliate links

**Comment by darigovresearch** [comment]
Do you want to set some up for Packt & amazon?

Some people like supporting the author of the book through them so may be worth your time if interested

**Comment by aloctavodia** [comment]
Packt provided this link https://packt.link/Osvaldo
