### ISSUE TITLE
Softmax function in aesara

### ISSUE THREAD

**Issue by rm10075** [aloctavodia/BAP#86]
Hi,

I was trying to run the code for the Softmax regression example in Chapter 4 using the Aesara (rather than Theano) Softmax function. It looked like the aesara.tensor.nnet subpackage had been [removed](https://github.com/aesara-devs/aesara/issues/674) but I was hoping [this](https://aesara.readthedocs.io/en/latest/reference/tensor/_autosummary/[aesara.tensor.special.softmax](https://aesara.readthedocs.io/en/latest/reference/tensor/_autosummary/aesara.tensor.special.softmax.html#aesara.tensor.special.softmax).html#aesara.tensor.special.softmax) might do the trick but was getting a "NotImplementedError: Cannot convert μ to a tensor variable." upon running the following code:

with pm.Model() as model_s:
    α = pm.Normal('α', mu=0, sigma=5, shape=3)
    β = pm.Normal('β', mu=0, sigma=5, shape=(4,3))
    μ = pm.Deterministic('μ', α + pm.math.dot(x_s, β))
    θ = aesara.tensor.special.softmax(μ)
    yl = pm.Categorical('yl', p=θ, observed=y_s)
    idata_s = pm.sample(2000, target_accept=0.9, return_inferencedata=True)

Any suggestions greatly appreciated.

Thanks,

Rich

**Comment by rm10075** [comment]
Please ignore, fixed by using PyTensor instead of theano:

with pm.Model() as model_s:
    α = pm.Normal('α', mu=0, sigma=5, shape=3)
    β = pm.Normal('β', mu=0, sigma=5, shape=(4,3))
    μ = pm.Deterministic('μ', α + pm.math.dot(x_s, β))
    θ = pytensor.tensor.special.softmax(μ)
    yl = pm.Categorical('yl', p=θ, observed=y_s)
    idata_s = pm.sample(2000, target_accept=0.9, return_inferencedata=True)

**Comment by aloctavodia** [comment]
glad you solve it!
