### ISSUE TITLE
Text below Code 4.5 in Chapter 4

### ISSUE THREAD

**Issue by KerrisBay** [aloctavodia/BAP#92]
The NegativeBinomial distribution has two parameters, the mean $\mu$ and a dispersion parameter $\alpha$. The variance of NB is $\mu + \frac{\mu^2}{\alpha}$, so the larger the value of $\alpha$ the **larger** the variance. 
 
Variance should be lower when $\alpha$ is larger. 
 
Otherwise, a great book. I really enjoy reading it. :-)

**Comment by aloctavodia** [comment]
Hi @KerrisBay, thanks for taking the time to report this issue. Notice this has already been reported and it's listed in the Errata. https://github.com/aloctavodia/BAP3/blob/main/errata.md

Glad that you are enjoying the book!
